Movie info
codingknite/moviehouse pull request #3
Opened 2021-03-25 15:01 UTC by codingknite

2021-03-25 15:02 UTC, codingknite commented
I fixed all the recommendations you gave on the other PR

2021-03-25 16:00 UTC, codingknite commented
I also think I made a mistake with the custom hook for react query. For some reason it's return data even though it's undefined

2021-03-25 23:24 UTC, idiglove requested changes

2021-03-25 23:24 UTC, idiglove commented on src/components/CastItem.jsx
> +          {/* <img src={baseUrl + `/${profilePath}`} alt={name} /> */}
remove unnecessary comments pls

2021-03-25 23:24 UTC, idiglove commented on src/components/MovieCast.jsx
> +  console.log(actorId);
this one too

2021-03-25 23:24 UTC, idiglove commented on src/components/SlideMovieCards.jsx
> +                      <BsIcons.BsHeartFill />
im not a fan of using react-icons, look at the size of it in npm

2021-03-25 23:24 UTC, idiglove commented on src/pages/Homepage.jsx
> +  if (trendingError) throw trendingError;
what does throw do? UX wise, I think user should see a good error message

2021-03-25 23:24 UTC, idiglove commented on src/utils/settings.js
> +};
hmm these settings look a lot similar. do we really need to separate them?

2021-03-26 09:35 UTC, codingknite commented on src/components/CastItem.jsx
> +          {/* <img src={baseUrl + `/${profilePath}`} alt={name} /> */}
Oh yeah I need that part....temporarily commented out

2021-03-26 09:35 UTC, codingknite commented on src/components/SlideMovieCards.jsx
> +                      <BsIcons.BsHeartFill />
Good Lord it's 36mb....I like it because it's so easy to use. What other options are there

2021-03-26 09:36 UTC, codingknite commented on src/pages/Homepage.jsx
> +  if (trendingError) throw trendingError;
I have those errors for dev't. In production the error boundary will be a UX friendly component

2021-03-26 09:37 UTC, codingknite commented on src/utils/settings.js
> +};
🤦 don't know how I missed that

2021-03-26 09:38 UTC, idiglove commented on src/pages/Homepage.jsx
> +  if (trendingError) throw trendingError;
Just for curiosity can you show me how this error boundary looks like?

2021-03-26 09:46 UTC, codingknite commented on src/pages/Homepage.jsx
> +  if (trendingError) throw trendingError;
![errorB](https://user-images.githubusercontent.com/70036189/112613220-e9fa4700-8e30-11eb-95a1-31a475ca9389.png)

The error boundary is from a plugin called `react-error-boundary`.
The component that is rendered is the `Error Fallback`

2021-03-26 09:58 UTC, idiglove commented on src/pages/Homepage.jsx
> +  if (trendingError) throw trendingError;
I mean what would the user actually see?

2021-03-26 10:09 UTC, codingknite commented on src/pages/Homepage.jsx
> +  if (trendingError) throw trendingError;
![x](https://user-images.githubusercontent.com/70036189/112616230-85d98200-8e34-11eb-8fb7-5cce0ec0f438.png)

2021-03-26 10:12 UTC, idiglove commented on src/pages/Homepage.jsx
> +  if (trendingError) throw trendingError;
hmm for UX., one, that doesnt look good. two, that error message doesnt mean anything to the user
You also need to know these skills if you wanna sell yourself to companies ;)

2021-03-26 11:25 UTC, codingknite commented on src/pages/Homepage.jsx
> +  if (trendingError) throw trendingError;
You're right. I'm going to make the component visually appealing

2021-03-26 14:25 UTC, codingknite commented
I fixed all the bugs...thanks for your help

2021-03-26 14:33 UTC, idiglove commented on src/pages/Biography.jsx
> +  //   console.log(bio);
do we need all these comments?

2021-03-26 14:34 UTC, idiglove commented on src/utils/settings.js
> +};
it's still here :P

2021-03-26 14:35 UTC, idiglove commented on src/utils/useApiCalls.js
> +    return { nowPlaying, trending, comingSoon }
why are we doing this? isnt isLoading from react-query enough?

2021-03-28 09:31 UTC, codingknite commented on src/utils/useApiCalls.js
> +    return { nowPlaying, trending, comingSoon }
That was from the Previous PR...i deleted this file all together in this one. That was actually part of why I was getting the undefined error

2021-03-28 18:45 UTC, merged