Watchlist & Favorites
codingknite/moviehouse pull request #5
Opened 2021-04-01 16:10 UTC by codingknite

2021-04-01 23:33 UTC, idiglove commented on src/components/MovieCards.jsx
> +        width: 16.1%;
cant we just make 16%? haha

2021-04-01 23:34 UTC, idiglove commented on src/pages/Genres.jsx
> +
can you explain whats happening here?

2021-04-01 23:35 UTC, idiglove commented on src/reducers/markedReducer.js
> +            }
can be simplified to: 

if (marked.includes(action.payload)) {
                const removedId = marked.filter((movie) => movie !== action.payload);
                return [...removedId];
}

 return [...marked, action.payload];

2021-04-01 23:36 UTC, idiglove commented on src/reducers/markedReducer.js
> +            }
same here

2021-04-01 23:36 UTC, idiglove requested changes
Nice, i have some comments tho

2021-04-02 07:08 UTC, codingknite commented on src/components/MovieCards.jsx
> +        width: 16.1%;
Lol Okay haha

2021-04-02 07:10 UTC, codingknite commented on src/pages/Genres.jsx
> +
In the reducer "initState" initializes the state the 1 so when the genreId on a page changes...the API call starts from page 1.
Before, the genreId would change and the page still loads from the current page number in the state

2021-04-02 07:11 UTC, codingknite commented
> 
> 
> Nice, i have some comments tho

Nice. Bring em on

2021-04-02 07:13 UTC, idiglove commented on src/pages/Genres.jsx
> +
isnt it good UX to stay at current page?

2021-04-02 07:16 UTC, codingknite commented on src/pages/Genres.jsx
> +
I don't think so...Imagine someone was browsing through animated movies and they went up to page 10 but then decided to checkout scifi movies....the API call would pull up page 11....see now they just missed 10 pages 😄

2021-04-02 07:18 UTC, idiglove commented on src/pages/Genres.jsx
> +
hmm i see, i might be missing something, but sounds good then

2021-04-02 07:22 UTC, codingknite commented on src/pages/Genres.jsx
> +
Let me show you a demo.
Also, what other comments did you have?

2021-04-02 07:27 UTC, idiglove commented on src/pages/Genres.jsx
> +
look under Conversation tab

2021-04-02 07:36 UTC, codingknite commented on src/pages/Genres.jsx
> +
I'm sorry but is this not the conversation tab?

2021-04-02 07:37 UTC, idiglove commented on src/pages/Genres.jsx
> +
![Screen Shot 2021-04-02 at 3 37 14 PM](https://user-images.githubusercontent.com/29911508/113393490-52b16880-93c9-11eb-8329-d1c4c67326f7.png)
look at all the conversations here

2021-04-02 07:44 UTC, codingknite commented on src/pages/Genres.jsx
> +
![shot](https://user-images.githubusercontent.com/70036189/113394022-35b46f80-93a0-11eb-983d-5e0390117664.png)

I did. I was alluding to what you said here. I thought you had other comments besides everything you have said so far.

2021-04-02 07:49 UTC, idiglove commented
@codingknite  
![Screen Shot 2021-04-02 at 3 49 33 PM](https://user-images.githubusercontent.com/29911508/113394563-0bc47280-93cb-11eb-97d0-8160c7b724dc.png)
clearly u didnt look hard enough ;P

2021-04-02 07:56 UTC, codingknite commented
Lol...I saw those...I just didn't react to them. Just went ahead and worked on them. i guess thats it then. sorry po :)

2021-04-05 19:32 UTC, codingknite commented
I've worked on this project for way too long lol 😄 Def finishing it this week

2021-04-05 23:45 UTC, idiglove commented on src/components/MovieCards.jsx
> +        width: 16.1%;
this is still the same..

2021-04-05 23:46 UTC, idiglove commented on src/components/NavBar.jsx
> +                  {favorites.length > 0 ? ` (${favorites.length})` : null}
just do `{favorites.length > 0 && ` (${favorites.length})`}`

2021-04-05 23:48 UTC, idiglove requested changes
few changes :)

2021-04-06 20:42 UTC, merged